import 'package:fitness_flutter/core/const/path_constants.dart';
import 'package:fitness_flutter/core/const/text_constants.dart';
import 'package:fitness_flutter/data/exercise_data.dart';
import 'package:fitness_flutter/data/workout_data.dart';
import 'package:fitness_flutter/screens/onboarding/widget/onboarding_tile.dart';

class DataConstants {
  // Onboarding
  static final onboardingTiles = [
    OnboardingTile(
      title: TextConstants.onboarding1Title,
      mainText: TextConstants.onboarding1Description,
      imagePath: PathConstants.onboarding1,
    ),
    OnboardingTile(
      title: TextConstants.onboarding2Title,
      mainText: TextConstants.onboarding2Description,
      imagePath: PathConstants.onboarding2,
    ),
    OnboardingTile(
      title: TextConstants.onboarding3Title,
      mainText: TextConstants.onboarding3Description,
      imagePath: PathConstants.onboarding3,
    ),
  ];

  // Workouts
  static final List<WorkoutData> workouts = [
    WorkoutData(
        id: 'workout1',
        title: TextConstants.yogaTitle,
        exercises: TextConstants.yogaExercises,
        minutes: TextConstants.yogaMinutes,
        currentProgress: 0,
        progress: 3,
        image: PathConstants.yoga,
        exerciseDataList: [
          ExerciseData(
            id: 'exercise1',
            title: TextConstants.reclining,
            minutes: TextConstants.recliningMinutes,
            progress: 0,
            video: PathConstants.recliningVideo,
            description: TextConstants.warriorDescription,
            steps: [
              TextConstants.warriorStep1,
              TextConstants.warriorStep2,
              TextConstants.warriorStep1,
              TextConstants.warriorStep2,
              TextConstants.warriorStep1,
              TextConstants.warriorStep2,
            ],
          ),
          ExerciseData(
            id: 'exercise2',
            title: TextConstants.cowPose,
            minutes: TextConstants.cowPoseMinutes,
            progress: 0,
            video: PathConstants.cowPoseVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            id: 'exercise3',
            title: TextConstants.warriorPose,
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0,
            video: PathConstants.warriorIIVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
        ]),
    WorkoutData(
        id: 'workout2',
        title: TextConstants.pilatesTitle,
        exercises: TextConstants.pilatesExercises,
        minutes: TextConstants.pilatesMinutes,
        currentProgress: 0,
        progress: 4,
        image: PathConstants.pilates,
        exerciseDataList: [
          ExerciseData(
            id: 'exercise4',
            title: TextConstants.reclining,
            minutes: TextConstants.recliningMinutes,
            progress: 0,
            video: PathConstants.recliningVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            id: 'exercise5',
            title: TextConstants.cowPose,
            minutes: TextConstants.cowPoseMinutes,
            progress: 0,
            video: PathConstants.cowPoseVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            id: 'exercise6',
            title: TextConstants.warriorPose,
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0,
            video: PathConstants.warriorIIVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            id: 'exercise7',
            title: TextConstants.warriorPose,
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0,
            video: PathConstants.warriorIIVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
        ]),
    WorkoutData(
        id: 'workout3',
        title: TextConstants.fullBodyTitle,
        exercises: TextConstants.fullBodyExercises,
        minutes: TextConstants.fullBodyMinutes,
        currentProgress: 0,
        progress: 3,
        image: PathConstants.fullBody,
        exerciseDataList: [
          ExerciseData(
            id: 'exercis8',
            title: TextConstants.reclining,
            minutes: TextConstants.recliningMinutes,
            progress: 0,
            video: PathConstants.recliningVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            id: 'exercise9',
            title: TextConstants.cowPose,
            minutes: TextConstants.cowPoseMinutes,
            progress: 0,
            video: PathConstants.cowPoseVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            id: 'exercise10',
            title: TextConstants.warriorPose,
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0,
            video: PathConstants.warriorIIVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
        ]),
    WorkoutData(
      id: 'workout4',
      title: TextConstants.stretchingTitle,
      exercises: TextConstants.stretchingExercises,
      minutes: TextConstants.stretchingMinutes,
      currentProgress: 0,
      progress: 5,
      image: PathConstants.stretching,
      exerciseDataList: [
        ExerciseData(
          id: 'exercise11',
          title: TextConstants.reclining,
          minutes: TextConstants.recliningMinutes,
          progress: 0,
          video: PathConstants.recliningVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise12',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise13',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise14',
          title: TextConstants.cowPose,
          minutes: TextConstants.cowPoseMinutes,
          progress: 0,
          video: PathConstants.cowPoseVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
        ExerciseData(
          id: 'exercise15',
          title: TextConstants.warriorPose,
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0,
          video: PathConstants.warriorIIVideo,
          description: TextConstants.warriorDescription,
          steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
        ),
      ],
    ),
  ];

  // static final List<WorkoutData> homeWorkouts = [
  //   WorkoutData(
  //     id: 'workout5',
  //     title: TextConstants.yogaTitle,
  //     exercises: TextConstants.yogaExercises,
  //     minutes: TextConstants.yogaMinutes,
  //     currentProgress: 0,
  //     progress: 3,
  //     image: PathConstants.cardio,
  //     exerciseDataList: [
  //       ExerciseData(
  //         id: 'exercise16',
  //         title: TextConstants.reclining,
  //         minutes: TextConstants.recliningMinutes,
  //         progress: 0,
  //         video: PathConstants.recliningVideo,
  //         description: TextConstants.warriorDescription,
  //         steps: [
  //           TextConstants.warriorStep1,
  //           TextConstants.warriorStep2,
  //           TextConstants.warriorStep1,
  //           TextConstants.warriorStep2,
  //           TextConstants.warriorStep1,
  //           TextConstants.warriorStep2,
  //         ],
  //       ),
  //       ExerciseData(
  //         id: 'exercise17',
  //         title: TextConstants.cowPose,
  //         minutes: TextConstants.cowPoseMinutes,
  //         progress: 0,
  //         video: PathConstants.cowPoseVideo,
  //         description: TextConstants.warriorDescription,
  //         steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
  //       ),
  //       ExerciseData(
  //         id: 'exercise18',
  //         title: TextConstants.warriorPose,
  //         minutes: TextConstants.warriorPoseMinutes,
  //         progress: 0,
  //         video: PathConstants.warriorIIVideo,
  //         description: TextConstants.warriorDescription,
  //         steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
  //       ),
  //     ],
  //   ),
  //   WorkoutData(
  //     id: 'workout6',
  //     title: TextConstants.armsTitle,
  //     exercises: TextConstants.armsExercises,
  //     minutes: TextConstants.armsMinutes,
  //     currentProgress: 0,
  //     progress: 3,
  //     image: PathConstants.cardio,
  //     exerciseDataList: [
  //       ExerciseData(
  //         id: 'exercise19',
  //         title: TextConstants.reclining,
  //         minutes: TextConstants.recliningMinutes,
  //         progress: 0,
  //         video: PathConstants.recliningVideo,
  //         description: TextConstants.warriorDescription,
  //         steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
  //       ),
  //       ExerciseData(
  //         id: 'exercise20',
  //         title: TextConstants.cowPose,
  //         minutes: TextConstants.cowPoseMinutes,
  //         progress: 0,
  //         video: PathConstants.cowPoseVideo,
  //         description: TextConstants.warriorDescription,
  //         steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
  //       ),
  //       ExerciseData(
  //         id: 'exercise21',
  //         title: TextConstants.warriorPose,
  //         minutes: TextConstants.warriorPoseMinutes,
  //         progress: 0,
  //         video: PathConstants.warriorIIVideo,
  //         description: TextConstants.warriorDescription,
  //         steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
  //       ),
  //     ],
  //   ),
  // ];

  // Reminder
  static List<String> reminderDays = [
    TextConstants.everyday,
    TextConstants.monday_friday,
    TextConstants.weekends,
    TextConstants.monday,
    TextConstants.tuesday,
    TextConstants.wednesday,
    TextConstants.thursday,
    TextConstants.friday,
    TextConstants.saturday,
    TextConstants.sunday,
  ];
}
